name: Notify GitHub Discussions to Slack

on:
  workflow_call:
    inputs:
      slack_user_mapping_file:
        description: 'Path to JSON file with GitHub username to Slack user ID mapping.'
        required: false
        type: string
        default: '.github/github-username-slack-mapping.json'
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      SLACK_USER_MAPPING_JSON:
        required: false

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v6
      - name: Notify Slack
        uses: jum8ys/github-discussions-slack-notifier@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_user_mapping_file: ${{ inputs.slack_user_mapping_file }}
          slack_user_mapping_json: ${{ secrets.SLACK_USER_MAPPING_JSON }}
