name: Notify GitHub Discussions to Slack

on:
  workflow_call:
    inputs:
      github_to_slack_user_mapping_file:
        description: 'Path to JSON file with GitHub username to Slack user ID mapping.'
        required: false
        type: string
        default: '.github/github-username-slack-mapping.json'
      notify_discussion_created:
        description: 'Notify on new discussions.'
        required: false
        type: string
        default: 'true'
      notify_comment_created:
        description: 'Notify on new discussion comments.'
        required: false
        type: string
        default: 'true'
      notify_answered:
        description: 'Notify when a discussion is marked as answered.'
        required: false
        type: string
        default: 'true'
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      GITHUB_TO_SLACK_USER_MAPPING_JSON:
        required: false

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v6
      - name: Notify Slack
        uses: jum8ys/github-discussions-slack-notifier@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github_to_slack_user_mapping_file: ${{ inputs.github_to_slack_user_mapping_file }}
          github_to_slack_user_mapping_json: ${{ secrets.GITHUB_TO_SLACK_USER_MAPPING_JSON }}
          notify_discussion_created: ${{ inputs.notify_discussion_created }}
          notify_comment_created: ${{ inputs.notify_comment_created }}
          notify_answered: ${{ inputs.notify_answered }}
